"""포켓몬 도트 (PokeAPI sprites: Gen VII icons, 에몽가는 Gen V black-white 2배 축소) -> 픽셀 행/팔레트."""

ICONS = {
    "피카츄": (['......AA.............', '.....ABA.........AA..', '.....ABA........ACDA.', '....ADDA....AAAACDDDA', '....ADEA..AABBBCDDDDA', '...AADA..ACCBBDDDDDA.', '..ADCCCAACCCBDDDDDA..', '.ACCCCCCECCBDDDDDA...', '.ACCCCDCCCEAADDDA....', 'ACCCCDFACCCA.ADDDA...', 'ACECCCABCCCCA.ADDA...', '.ACCCCCGGCCCCADDA....', 'AHBDCCCGGCCCIBJA.....', '.AAADDCCBCCCCCBJA....', '....ADDBCCBCCIBA.....', '....ADDDBBCCCCA......', '.....ADDCCCCCBA......', '......AAACCCCA.......', '.........AACA........', '...........A.........'],
             {'A': '#313131', 'B': '#525252', 'C': '#f7d631', 'D': '#c5a529', 'E': '#9c8442', 'F': '#ffffff', 'G': '#f76352', 'H': '#bd9421', 'I': '#b57329', 'J': '#a56b31'}),
    "파이리": (['.................A...', '.....AAA........ABA..', '...AACCBA.......ABBA.', '..ACCCCCBA......ABBA.', '..ACCCCCCA.....ABBCBA', '.ACCCCBCCBA....ABCDBA', '.ACCCBEACCA....ABDDBA', 'ACCCCFGACBA.....ADBA.', 'ACCCCCAABBA.....ABA..', '.ABCCCBBBBBA....ACA..', '..AABBBBBBBA...ACCA..', '....AAHBBIBBA.ABCA...', '.....AJJIFCBBABBBA...', '.....AJJICBIBBIBA....', '....AFFJJIIBBBIA.....', '....AKFIHHBBBFA......', '.....AAAAIFBFA.......', '.........AEFEA.......', '..........AAA........'],
             {'A': '#313131', 'B': '#d66342', 'C': '#f79429', 'D': '#f7f729', 'E': '#ffffff', 'F': '#ad5242', 'G': '#196363', 'H': '#debd84', 'I': '#525252', 'J': '#f7e69c', 'K': '#bdbdbd'}),
    "파치리스": (['.................A....', '................ABA...', '..............A.ABA.AA', '.............ABABBCABA', '.....A.......ABCBBCBDA', '....ADA.....ACBBDBDBA.', '...AEDA...AAFGBBBBBBA.', '...ADEA..ABCFBBBGFFGDA', '..AGFBBAABBCGBBGFFFFGA', '.AHFGBBFFBBCBBBFFFFFFA', '.FIFBFFFFBFCBBGFFIIFHA', 'ACFFFFIHFFFHCBFFIHHHA.', 'AFFFFHFAFFFFCBFFCHHA..', 'AFHFFFAIFJJHCBFFCAA...', '.AFKKFFFJLLCBGFFA.....', '..ACMHHHLLCDBFFHA.....', '...AIHCCHCHDDHHA......', '..AFCCFFICDDHHHA......', '..AIHCCFFICHHHA.......', '...AIFFFFFCHAA........', '...AHIFFFFAA..........', '....AAAFFA............', '.......AA.............'],
             {'A': '#313131', 'B': '#73c5ff', 'C': '#525252', 'D': '#63a59c', 'E': '#427b73', 'F': '#ffffff', 'G': '#9cdeff', 'H': '#bdbdbd', 'I': '#848473', 'J': '#f7d631', 'K': '#b56373', 'L': '#d6ad00', 'M': '#de7b84'}),
    "망나뇽": (['..A.......AA.............', '.ABA.....ACDA...AA.......', '.ABA....ACCCA..ABA.......', '..ABAA..ADECDAABA..AA....', '...AFFAAGGDDBBBA..AGGA...', '....ADAGCCDBDAA...AGEGA..', '.....AGGGDBDGA...AGGEEGA.', '...AADGGGGCGGA...AGEEHGA.', '.AACDGGGIAGGGGA.AGEHEHHGA', 'AJCDGGGGAAIGGGAAGEHHAAAGA', 'ACCDGGGGCDIGGGGGAAHA...A.', '.ACDGGCGGGGGGGGGGGAA.....', '..AAAGGGGCDGGDGGGGGGA..A.', '.....AADDDBCGGDGGGGIDAACA', '.......ADBBBGGGDGICDCCCCA', '......ACDFFFFGCGDDDCCCCA.', '......ACCDBBBCGGGGDCCCA..', '.......ADCDFFCGGGGGDAA...', '........AAAABDGGGGGA.....', '............AAAGGGA......', '...............AICIA.....', '................AAA......'],
             {'A': '#313131', 'B': '#f7e6bd', 'C': '#b5845a', 'D': '#525252', 'E': '#4a9484', 'F': '#d6c57b', 'G': '#f7b563', 'H': '#52bda5', 'I': '#ffffff', 'J': '#bdbdb5'}),
    "잠만보": (['..................AA.......', '.................ABAA......', '...............AABBBA..AAAA', '..............ACDDDEEAAFBEA', '.........AAA.ADFDDDDDDEEEEA', '........AEEEAACCDDFFCDDEEBA', '.......AEEGFDDDDCCDDCFDEBA.', '.......AEGFFDDDDDDCDDDDBBA.', '.......AEFFDDDDFFFFFDDBBBA.', '.......FFDDDDDFEEEEEFBBBFA.', '......ADDDDDDHFEEEEEEFBFA..', '......ADDDDDDHFEEEEEEBBBA..', '.AA..AHDDDDDDDHFFEEEBBBBA..', 'ADCAAAHHDDDDDDDDHBBBBBBBA..', 'ACDDFBBHHHDDDDHHBBBBBBBBA..', 'AHHDHFBHHHHHFFFBBBBBBBBBA..', '.AHHHFBBHHHFGIGFBBBBBBBA...', '.AHHHBBBBHFDHDHDFBBBBBBA...', '..AHHABBBBFDDDDDFBBBBBA....', '...AA.AABBFDIIDHHFBBBA.....', '........AAFIIIIHHFBAA......', '..........AIIIIHFAA........', '...........AIIHFA..........', '............AAAA...........'],
             {'A': '#313131', 'B': '#426b8c', 'C': '#b58c5a', 'D': '#ffefc5', 'E': '#52849c', 'F': '#525252', 'G': '#ffffff', 'H': '#cebd94', 'I': '#9c7342'}),
    "에몽가": (['....A....AAA................', '...BCC..ACCBC...............', '..BCCABDCBEFD...............', '..DAAAACCEGHD...............', '..DAAADCBGID................', '..DACCCGCCD.................', '..JCGCGBGCC.............BBBB', '.JBGGGBCBGCB..........BBCCB.', '.JBCCGDBDGCC.J.......BCCCDBB', '.JDCGKKGHHCADDD.....BCCCDBCD', '.DGKKKKLHFADGGDD...BCCCCCC..', 'DDDGKMMLEADGGCFHD.BAACCCAB..', 'JGCDDELADAGGDDHHHDBAAAACC...', 'BDGGDDDDEGGDDFHHHDDDAAAA....', 'JFDDDDGGGGGGJFHHHHDBAAD.....', '.DFFFFGGGGGGDDHHHHDAD.......', '.DFFFFBGGGGGGDHHHD..........', '..DFFHDGGGGGEDHHD...........', '...JHHHDDDBDDDDD............', '.....J..DNJ..DD.............', '.........D..................'],
             {'A': '#313131', 'B': '#202020', 'C': '#414141', 'D': '#101010', 'E': '#cdc5ac', 'F': '#d5a431', 'G': '#ffffff', 'H': '#ffd500', 'I': '#b48b08', 'J': '#6a5a31', 'K': '#943941', 'L': '#c56a62', 'M': '#e69483', 'N': '#bda473'}),
}

# 에몽가: 프로필 사진과 같은 Gen V 도트 원본 (브라우저가 매끈하게 축소)
EMOLGA_PNG = ("iVBORw0KGgoAAAANSUhEUgAAADcAAAApCAYAAACRB7GtAAAFJElEQVR42s2aIXTiShSG//RU8NyMXEfk1k3dA5d1wb06wFFV6raOyuJ4Dla1rlQtElzjoI5xrAxuZSJxeQJmdjKZSUJfKdxz9hxOkk3uN/+dO/feUwcfaIyxRL/GOXdwJDvfx2Gbo+IZQkjmXrVaTdbrtXNycIyxRHXY5Kj+DACEYSh/u64LAEcBtMJVq9WM05TSlKOEkNQzAmr6QOW1xn14rKiEYwPbrTgAII5j+TuKIqzXa4cQkjDGUmCT8QAA8HvRhvvlq7xXvw0Rx/GnK3eWdzOO4xSYUI8QkoJXwQDgS+0Z4e9fOLZlwpIQklBKM1CG54zXL2tX29BctHHBuHj6NLOlbmEYwqSagAKA6eAvNPzNVuk6OUpIFoalCcykmgp2SlaoXBRFatrP3FdVPCXVrNlSJIwoijLOCwuCAADgeZ689t1/Oxmw3KNAVSUIAgkhoHQT9znnItM6xw5L457za1Tur1brMqNWnpKMMWsmPbRVq9VE/ZdZ3ZsmS0bjpVTDBiRUVUutp6c7jHf/NwxDfEbJJaJM3/+c83RYqmB55rpu6khQAUV4HhpO3zpqRt8VH86ZzfnlYpJbuaiJRDURxq7rplb1o0PPdd0MGOdcgqUSilBNqJIXkrsSTIKqx4WeXD4qsdiU0sCc3HMujmOoq2KCjKJIdAh4nT6Wcu6mue35Xmb7F9HVajVRF9QGpkfKuS3sijJkSq3VzteLxPgOERWUUrEwSVlAvUMxgRFCMsU85zwL9zp9xLfGtYQKxnf4Ncomme4iSIPtfi/jn4jjGGEYipVOOt2eXBCxlwkhhYB5YAJKr5pyE8pl7UqqMqp5RjAAWHQ7mWsrnv7Q08P2XWrtqb6fEJK8BywMQzDGyicU8bFoHsvwGtU8bezgwr3Ypf9ViNroCVg5Kaj2v9uP60lGKt66xMssxHNvg4a/MZZpYo/ltVZlEsqZ2BNiw684k6EmQw/APy1Pgqm2jH/K3xu3lwvmeR66PjAfurIGjeZxroKmhlm/L0JUTyhnIoONxksQQlC/DbHiDKvxpQRkzEW4ys5CxP7ZuD28bTxc3/YxGXbM5dn4Ttadf5rYrT33NhJQVa0IknNuDVEZlnrJxTnHYNAB+/p3ar+o+6zS8rcf+PWG0SiQe8GmGqUU86FrhFO7CBtc0STAFJaOreRSPyBA5Ys0IDXTmhrXIjAAmM4qaPcrIISgDJwKaSsW5MFnqjRMoPqL7++vJHgRWB6crp4oJspMB2xHyvl6vXZumizp+hSUUkyGHXitgfHA9jwPg4eudShkAmv65cDE3mv3iZyLRlFkhRQRk3dWpg7x+dDFaBbg6narlA6a18/Zqpiu0g8WWcPfAP1K6jjQo6YMlLVZFal6PnQxmQUQH6CU5nYKNhuNlxjN9i+STVAiBMuWbqmuoOsXODrbOruvUUoRzeNyz9aJsU98T3chlXuZHW6mH0URaL240pjOKkaV3ts2nakrUxQ+XR977aF9rd2v/G8g654rUu+CccwW0bs+9Dp9zFVPqHaw6Vccx079NrSC6X1aWStKRCvOpGqfMpTNO3hpnVgPfBvUt8Y1mr6Lrv/nfSvOIBbzEHNOJ28soDpiymrqAb9cTBCHb+jcTzLqEkLw9LA96CezIBX+hxzeOmXmHqNeGrDb3/ZvP164o7crNmcJIYnoGCazAD9eDv+HAM4+wx1humM3TZZc+V6u44SQpOm7ELOUUxi3l63Mk5smS5IkSfSF0J/La0xPGvDUHP8PQE5X8Hv0VgYAAAAASUVORK5CYII=", 55, 41)
